.PHONY: clean All

All:
	@echo "----------Building project:[ cycle-while-do - Debug ]----------"
	@cd "cycle-while-do" && "$(MAKE)" -f  "cycle-while-do.mk"
clean:
	@echo "----------Cleaning project:[ cycle-while-do - Debug ]----------"
	@cd "cycle-while-do" && "$(MAKE)" -f  "cycle-while-do.mk" clean
